# Generated by Django 4.2.28 on 2026-02-24 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(help_text='12-digit AWS account ID', max_length=12, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ROOT', 'Root Account'), ('MEMBER', 'Member Account')], default='MEMBER', max_length=10)),
                ('environment', models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGING', 'Staging'), ('DEVELOPMENT', 'Development'), ('SHARED', 'Shared Services')], default='DEVELOPMENT', max_length=20)),
                ('organization_role_name', models.CharField(default='OrganizationAccountAccessRole', help_text='IAM role name to assume in this account', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_discovery_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AWS Account',
                'verbose_name_plural': 'AWS Accounts',
                'ordering': ['account_name'],
            },
        ),
    ]
