# Generated by Django 4.2.28 on 2026-02-24 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-box', help_text='Bootstrap Icons class', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resources_discovered', models.IntegerField(default=0)),
                ('resources_updated', models.IntegerField(default=0)),
                ('resources_new', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log_output', models.TextField(blank=True, default='')),
                ('aws_account', models.ForeignKey(blank=True, help_text='Null means all accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.awsaccount')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('asset_type', models.CharField(choices=[('AWS_SERVICE', 'AWS Service'), ('SELF_HOSTED', 'Self Hosted'), ('SAAS', 'SaaS'), ('ON_PREMISE', 'On Premise')], default='AWS_SERVICE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DECOMMISSIONED', 'Decommissioned'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=20)),
                ('criticality', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('aws_region', models.CharField(blank=True, default='', max_length=30)),
                ('aws_resource_id', models.CharField(blank=True, default='', max_length=500)),
                ('aws_resource_arn', models.CharField(blank=True, default='', max_length=1024)),
                ('aws_service_type', models.CharField(blank=True, choices=[('EC2', 'EC2'), ('EKS', 'EKS'), ('RDS', 'RDS'), ('ELASTICACHE', 'ElastiCache'), ('ALB', 'ALB'), ('NLB', 'NLB'), ('VPC', 'VPC'), ('LAMBDA', 'Lambda'), ('ECR', 'ECR'), ('COGNITO', 'Cognito'), ('OPENSEARCH', 'OpenSearch'), ('S3', 'S3'), ('IAM', 'IAM'), ('SNS', 'SNS'), ('SQS', 'SQS'), ('MSK', 'MSK'), ('CLOUDFRONT', 'CloudFront'), ('ROUTE53', 'Route53'), ('ACM', 'ACM'), ('SECRETSMANAGER', 'Secrets Manager'), ('OTHER', 'Other')], default='', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_addresses', models.JSONField(blank=True, default=list)),
                ('dns_names', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('version', models.CharField(blank=True, default='', max_length=100)),
                ('data_classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('STRICTLY_CONFIDENTIAL', 'Strictly Confidential')], default='INTERNAL', max_length=25)),
                ('gdpr_relevant', models.BooleanField(default=False)),
                ('contains_personal_data', models.BooleanField(default=False)),
                ('backup_enabled', models.BooleanField(default=False)),
                ('monitoring_enabled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_manually_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounts.awsaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('DEPENDS_ON', 'Depends On'), ('CONTAINS', 'Contains'), ('CONNECTS_TO', 'Connects To'), ('MANAGED_BY', 'Managed By')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='assets.asset')),
                ('target_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='assets.asset')),
            ],
            options={
                'unique_together': {('source_asset', 'target_asset', 'relationship_type')},
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['aws_resource_arn'], name='assets_asse_aws_res_d99891_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['aws_account', 'aws_region', 'aws_resource_id'], name='assets_asse_aws_acc_ef55ec_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asse_asset_t_529092_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['criticality'], name='assets_asse_critica_a56ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['aws_service_type'], name='assets_asse_aws_ser_f85639_idx'),
        ),
    ]
