# Generated by Django 4.2.28 on 2026-02-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
